# Generated by Django 3.2.2 on 2021-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_categoria',
            options={'verbose_name': 'T_categoria', 'verbose_name_plural': 'T_categorias'},
        ),
        migrations.CreateModel(
            name='T_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(to='Tienda.T_Categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'productos',
            },
        ),
    ]
