# Generated by Django 3.2.2 on 2021-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_alter_t_categoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_categoria',
            name='descripcion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
