# Generated by Django 3.2.2 on 2021-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_t_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_categoria',
            name='nombre',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
