# Generated by Django 3.2.2 on 2021-06-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_alter_t_categoria_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_categoria',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='t_categoria',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='t_categoria',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
