# Generated by Django 3.2.2 on 2021-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_auto_20210612_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categorias',
            },
        ),
        migrations.DeleteModel(
            name='T_Categoria',
        ),
        migrations.AlterField(
            model_name='t_producto',
            name='categorias',
            field=models.ManyToManyField(to='Tienda.Tienda_Categoria', verbose_name='Categorias'),
        ),
    ]
