# Generated by Django 3.2.2 on 2021-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0009_prueba_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_producto',
            name='categorias',
            field=models.ManyToManyField(to='Tienda.prueba_Categoria', verbose_name='Categorias'),
        ),
    ]
