# Generated by Django 3.2.2 on 2021-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0016_alter_t_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_producto',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
