# Generated by Django 3.2.2 on 2021-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0017_t_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_producto',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
