# Generated by Django 3.2.2 on 2021-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210602_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(to='Blog.Categoria', verbose_name='Categorias'),
        ),
    ]
